# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything:
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# enable color support of ls and also add handy aliases

if hash dircolors &> /dev/null; then # If command exists
	if [ "$TERM" != "dumb" ]; then
	    eval "`dircolors -b`"
	    alias ls='ls --color=auto'
	    #alias dir='ls --color=auto --format=vertical'
	    #alias vdir='ls --color=auto --format=long'
	fi
fi
# some more ls aliases
#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'

if hash byobu 2>/dev/null; then
  echo "[Screen]   Byobu";
  alias screen="byobu"
else
  echo "[Screen]   Default Screen";
fi


# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" -a -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

#. $HOME/projects/dotfiles/bin/prompt.sh

EDITOR=vim

export PATH=$PATH:$HOME/bin

export WORKON_HOME=$HOME/.virtualenvs
if [[ -e /usr/local/bin/virtualenvwrapper.sh ]];
then
	echo "[VEnv]     Available";
	source /usr/local/bin/virtualenvwrapper.sh
elif [[ -e /usr/bin/virtualenvwrapper.sh ]];
then
	echo "[VEnv]     Available";
	source /usr/bin/virtualenvwrapper.sh
else
	echo "[VEnv]     Not Installed";
fi

if [[ -e $HOME/Development/pear/bin ]];
then
	echo "[Pear]     Available";
	export PATH=$PATH:/Users/aquarion/Development/pear/bin
else
	echo "[Pear]     Not Available";
fi

if [[ -s "$HOME/.rvm/scripts/rvm" ]]
then
	. "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.
	echo "[RVM]      Available";
	if [[ -s "$HOME/.rvm/bin" ]];
	then
		export PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
	fi
else:
	echo "[RVM]      Not Available";
fi

if [[ -x "$HOME/bin/composer" ]]
then
	echo "[Composer] Available";
        export PATH=$PATH:$HOME/.composer/vendor/bin
else
	echo "[Composer] Not Available";
fi

### Added by the Heroku Toolbelt
if [[ -s "/usr/local/heroku" ]];
then
	echo "[Heroku]    Available";
	export PATH="/usr/local/heroku/bin:$PATH"
fi

if [[ -e ~/.bashrc.local ]];
then
	~/.bashrc.local
fi


if [[ -e ~/.bash_profile.local ]];
then
	source ~/.bash_profile.local
fi


if hash hub 2>/dev/null; then
  echo "[Git/Hub]   Available"
  alias git=hub
fi

if `which dropbox > /dev/null`;
then
	echo "[Dropbox]  $(dropbox status)"
fi
