# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything:
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# enable color support of ls and also add handy aliases

if hash dircolors &> /dev/null; then # If command exists
	if [ "$TERM" != "dumb" ]; then
	    eval "`dircolors -b`"
	    alias ls='ls --color=auto'
	    #alias dir='ls --color=auto --format=vertical'
	    #alias vdir='ls --color=auto --format=long'
	fi
fi
# some more ls aliases
#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'

if hash byobu 2>/dev/null; then
  echo "[VTerm]    Byobu";
  alias screen="byobu"
else
  echo "[VTerm]    Screen";
fi


# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" -a -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

#. $HOME/projects/dotfiles/bin/prompt.sh

EDITOR=vim

NOTCONF=''

export PATH=$PATH:$HOME/bin

export WORKON_HOME=$HOME/.virtualenvs
if [[ -e /usr/local/bin/virtualenvwrapper.sh ]];
then
	echo "[VEnv]     Available";
	source /usr/local/bin/virtualenvwrapper.sh
elif [[ -e /usr/bin/virtualenvwrapper.sh ]];
then
	echo "[VEnv]     Available";
	source /usr/bin/virtualenvwrapper.sh
else
	NOTCONF="${NOTCONF}Virtualenv, "
fi

if [[ -e $HOME/Development/pear/bin ]];
then
	echo "[Pear]     Available";
	export PATH=$PATH:/Users/aquarion/Development/pear/bin
else
	NOTCONF="${NOTCONF}Pear, "
fi

if [[ -s "$HOME/.rvm/scripts/rvm" ]]
then
	. "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.
	echo "[RVM]      Available";
	if [[ -s "$HOME/.rvm/bin" ]];
	then
		export PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
	fi
else
	NOTCONF="${NOTCONF}RVM, "
fi

if [[ -x "$HOME/bin/composer" ]]
then
	echo "[Composer] Available";
        export PATH=$PATH:$HOME/.composer/vendor/bin
else
	NOTCONF="${NOTCONF}Composer, "
fi

### Added by the Heroku Toolbelt
if [[ -s "/usr/local/heroku" ]];
then
	echo "[Heroku]    Available";
	export PATH="/usr/local/heroku/bin:$PATH"
else
	NOTCONF="${NOTCONF}Heroku, "
fi

if [[ -e ~/.bashrc.local ]];
then
	~/.bashrc.local
fi


if [[ -e ~/.bash_profile.local ]];
then
	source ~/.bash_profile.local
fi


if hash hub 2>/dev/null; then
  echo "[Git/Hub]  Available"
  alias git=hub
else
    echo -n "[Git/Hub]  Downloading... "
	if [[ ! -d ~/scratch ]]; then mkdir ~/scratch; 	fi
	if [[ ! -d ~/bin ]]; then mkdir ~/bin; 	fi

	HUBVERSION=2.2.3

	if [ "$(uname)" == "Darwin" ]; then
    	ARCH="darwin-amd64";    
	elif [[ `uname -i` -eq "x86_64" ]]; 
	then 
		ARCH="linux-amd64";
	elif [[ `uname -i` -eq "i686" ]]; 
	then 
		ARCH="linux-386";
	fi

    echo -ne "\r[Git/Hub]  Downloading...          "
	wget https://github.com/github/hub/releases/download/v$HUBVERSION/hub-linux-amd64-$HUBVERSION.tgz -O ~/scratch/hub.tgz -o ~/scratch/hub.log
    echo -ne "\r[Git/Hub]  Extracting ...          "
	tar vzxf ~/scratch/hub.tgz  -C ~/scratch/ >> ~/scratch/hub.log
    echo -ne "\r[Git/Hub]  Installing ...          "
	cp -v ~/scratch/hub-$ARCH-$HUBVERSION/bin/hub ~/bin/hub >> ~/scratch/hub.log
	echo -ne "\r[Git/Hub]  Cleaning up ...          "
	rm -vrf ~/scratch/hub.tgz ~/scratch/hub-$ARCH-$HUBVERSION >> ~/scratch/hub.log

    alias git=hub

	git version >> ~/scratch/hub.log

    echo -e "\r[Git/Hub]  Installed $HUBVERSION          "
fi

if `which dropbox > /dev/null`;
then
	echo "[Dropbox]  $(dropbox status)"
else
	NOTCONF="${NOTCONF}Dropbox, "
fi

echo "Not Available: ${NOTCONF}Ponies";